### ISSUE TITLE
move api repository to https://github.com/osmose-model/osmose-web-api

### ISSUE THREAD

**Issue by jhpoelen** [osmose-model/osmose-web-api#181]

**Comment by agruss2** [comment]
@barriern 
We would like to move the OSMOSE API repository developed for our bridge project/paper to https://github.com/osmose-model/
For this to happen, we would need @jhpoelen to be one of the owners of the osmose-model GitHub repository. 
Could you please make this happen? 
Thanks a lot!

**Comment by agruss2** [comment]
@barriern Thanks a lot!
@jhpoelen Could you please do the move? Also, when all the pre-publication steps you had identified have been implemented, could you please send me a list of all the new information I should include in the bridge paper so that we can point the reader to all the most-up-to-date GitHub respoitories, webpages, Zenodo resources, etc.? Many thanks!

**Comment by jhpoelen** [comment]
The osmose-web-api can be cited using https://doi.org/10.5281/zenodo.1411483 . This automatically points to the most recent version of the osmose-web-api . 
The osmose-web-api-js (the javascript library) can be cited using https://doi.org/10.5281/zenodo.1411481 . This also automatically points to the most recent version of the osmose-web-api .

**Comment by agruss2** [comment]
@jhpoelen Wondeful, thanks a lot!
