### ISSUE TITLE
move UI repository to https://github.com/osmose-model/osmose-web-ui

### ISSUE THREAD

**Issue by jhpoelen** [osmose-model/osmose-web-api#182]

**Comment by agruss2** [comment]
@barriern 
We would like to move the UI repository developed for our bridge project/paper to https://github.com/osmose-model/
For this to happen, we would need @jhpoelen to be one of the owners of the osmose-model GitHub repository. 
Could you please make this happen? 
Thanks a lot!

**Comment by agruss2** [comment]
@barriern Thanks a lot for having given ownership to Jorrit! 
@jhpoelen Could you please do the move? Also, when all the pre-publication steps you had identified have been implemented, could you please send me a list of all the new information I should include in the bridge paper so that we can point the reader to all the most-up-to-date GitHub respoitories, webpages, Zenodo resources, etc.? Many thanks!

**Comment by jhpoelen** [comment]
@FIN-casey could you please complete the following suggested steps to move the web UI to the osmose organization? 

1. rename the repository from ```FIN-casey.github.io``` to ```osmose-web-ui``` see https://help.github.com/articles/renaming-a-repository/ . 
2. request a transfer ownership of the repository to organization ```osmose-model```  see https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization .
3. ping me and I'll complete the transfer

Please let me know if you have any other questions / ideas.

**Comment by QQ-Sortiz** [comment]
Hello @jhpoelen,

I already renamed the github repository to osmose-web-ui but it still created a link pegged with fin-casey.  (http://fin-casey.github.io/osmose-web-ui/).

I also tried to transfer the ownership of the repository to you and Nicolas Barrier but transfer button is disabled. I attached a screenshot for your reference. 

![transfer](https://user-images.githubusercontent.com/26316138/45280874-a2c53880-b508-11e8-9c84-7f1b384c6fc4.JPG)

**Comment by barriern** [comment]
Hi 

Is it because you inverted both fields? I think osmose-model should be the organization name, and jhpoelen should be set into the first field (repository to confirm). But I am not sure.

**Comment by QQ-Sortiz** [comment]
Hello Nicolas,

Nice catch! I misunderstood the repository name to be the repository that will hold the transfer. I tried to transfer the osmose-web-ui repository but I don't have enough access credentials to create a repository on osmose-model. Could you help me with this? By the way, I am using FIN-casey for this transfer. Thanks!

**Comment by barriern** [comment]
Hi 
I have added the FIN-casey user to the osmose-model organization. Let me know if you now can create the repo.
Nicolas

**Comment by QQ-Sortiz** [comment]
Hello @barriern,

Still unable to transfer the repository to osmose-model. Same error. "You don’t have the permission to create repositories on osmose-model". Thanks!

**Comment by barriern** [comment]
Maybe I can try to create the repo. What would be the name of the repo?

**Comment by QQ-Sortiz** [comment]
Hello @barriern,

I successfully transferred the osmose-web-ui to osmose-model. I just accepted the invitation from you. Thanks!

Hello @jhpoelen,

Finish with the transfer. Thanks!

**Comment by barriern** [comment]
I have one more question. If I browse https://github.com/osmose-model/osmose-web-ui, the github directory shows up instead of the website, is it normal?

**Comment by QQ-Sortiz** [comment]
Hello @barriern,

You have to create github page for the repository. I was not able to create it because I am not owner of the account. Please see [https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/)

**Comment by barriern** [comment]
Hi @agruss2 . @jhpoelen, @QQ-Sortiz 
After some digging, the configuration wizard is now available from config.osmose-model.org or www.config.osmose-model.org. This is done via a redirection from OVH (where OSMOSE websites are hosted) to the GitHub repository. For this, I have renamed the osmose-web-ui repository into osmose-model.github.io. 
However, I have some questions for you. I see that there are three repositories related to the Web API: **osmose-model.github.io**, **osmose-web-api-js** and  **osmose-web-api**. My question is what are the purpose of each of them, and how do they interact? 
Thanks
Nicolas

**Comment by agruss2** [comment]
@barriern @jhpoelen @QQ-Sortiz @FIN-JBarile 
I just tried to run a test with the web application by going to FishBase website (e.g., https://www.fishbase.de/search.php) and then selecting "OSMOSE parameters" in the "Tools" section. 
Instead of reaching the first page of the web UI, I got the following message: 
'''
404
There isn't a GitHub Pages site here.

If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

GitHub Status — @githubstatus
'''
Do you know why is that and how this could please be fixed? 
Many thanks!

**Comment by barriern** [comment]
Hi Arnaud
This is because the Fishbase website points to http://fin-casey.github.io/. But since everything has migrated, the Fishbase website should now point to either 
http://www.config.osmose-model.org or http://osmose-model.github.io
Nicolas

**Comment by agruss2** [comment]
@barriern Yes, that's what I suspected! I'm therefore gonna open a new GitHub issue for Skit and Miel. Thanks a lot Nicolas and talk very soon!

**Comment by agruss2** [comment]
Since the migration has been successfully completed, we can now close the present issue; thanks a lot to you all!
